In [ ]:
# !pip install pyro-ppl==1.3.1

In [1]:
import sys
sys.path.append('../')
sys.path.append('../../')
from src.posterior_networks.PosteriorNetwork import PosteriorNetwork
import json
import numpy as np
import pandas as pd
import wandb
from dataset_manager.ClassificationDataset import MapillaryDataset
from src.results_manager.metrics_prior import confidence, brier_score, anomaly_detection
import torch
import torchvision.transforms as transforms
from sklearn.metrics import balanced_accuracy_score
import matplotlib.pyplot as plt
from src.posterior_networks.config import config
import os
os.environ["KMP_DUPLICATE_LIB_OK"]="TRUE"

/nfs/homedirs/zhz/anaconda3/envs/postnet/lib/python3.10/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
# train_df = pd.read_csv('/lab/project-1/train_label.csv')
val_df = pd.read_csv('/lab/project-1/val_label.csv')
test_df = pd.read_csv('/lab/project-1/test_label.csv')
regions = set(['g1', 'g2', 'g3', 'g4', 'g5', 'g6'])
classes = set(['regu', 'warn', 'comp', 'info'])
full_path = '/lab/project-1/final_models/effnet_oodg4_lat8_reg1e4_dens6_batch64_lr1e4__'
# full_path = '../../src/posterior_networks/models/resnet18_oodg3g4_RandAug_ops3_mag3_bins31'

config = json.load(open(f'{full_path}/config.json'))


# if 'class_encoding' in config: 
#     class_encoding = config['class_encoding']
# else:
#     class_encoding = {c: i for i, c in enumerate(sorted(train_df.label.unique()))}

if "N" in config:
    N = config['N']
else:
    N = train_df.label_encoded.value_counts().sort_index().values
N = torch.tensor(N)

print(N)

model = PosteriorNetwork(N=N,
                         n_classes=config['num_classes'],
                         hidden_dims=config['hidden_dims'],
                         kernel_dim=None,
                         latent_dim=config['latent_dim'],
                         architecture=config['architecture'],
                         k_lipschitz=config['k_lipschitz'],
                         no_density=config['no_density'],
                         density_type=config['density_type'],
                         n_density=config['n_density'],
                         budget_function=config['budget_function'],
                         batch_size=config['batch_size'],
                         lr=config['lr'],
                         loss=config['loss'],
                         dropout=config['dropout'],
                         regr=config['regr'],
                         seed=config['seed'])

model.load_state_dict(torch.load(f'{full_path}/best_model.pth')['model_state_dict'])
model.cuda()
transform_val_test = transforms.Compose([
    transforms.ToTensor(),
    transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])])

val_dataset = MapillaryDataset(val_df, transform = transform_val_test)

# use a dict to map ground truth vector of ID and OOD
ood_regions_classes = set(config['ood_regions'].split(','))
ood_regions = ood_regions_classes.intersection(regions)
ood_classes = ood_regions_classes.intersection(classes)

grd_truth = torch.tensor(val_df.region.isin(ood_regions).astype(int).values) # 0 as ID, 1 as OOD

tensor([ 7458,  3970, 21210,  9894])


Using cache found in /nfs/homedirs/zhz/.cache/torch/hub/pytorch_vision_main


In [3]:
config['density_type']

'iaf_flow'

In [3]:
# # if error in model loading:
# dict = torch.load(f'{full_path}/best_model.pth')['model_state_dict']
# older_val = dict['sequential.11.weight']
# dict['sequential.12.weight'] = dict.pop('sequential.11.weight')
# older_val = dict['sequential.11.bias']
# dict['sequential.12.bias'] = dict.pop('sequential.11.bias')
# torch.save(full_path,'./model_changed.pth')
# model.load_state_dict(dict)

<All keys matched successfully>

In [3]:
def compute_X_Y_alpha(model, loader, alpha_only=False):
    model.cpu()
    for batch_index, (X, Y) in enumerate(loader):
        X, Y = X.to('cpu'), Y.to('cpu')
        alpha_pred = model(X, None, return_output='alpha', compute_loss=False)
        # print('batch:', batch_index)
        if batch_index == 0:
            X_duplicate_all = X.to("cpu")
            orig_Y_all = Y.to("cpu")
            alpha_pred_all = alpha_pred.to("cpu")
        else:
            X_duplicate_all = torch.cat([X_duplicate_all, X.to("cpu")], dim=0)
            orig_Y_all = torch.cat([orig_Y_all, Y.to("cpu")], dim=0)
            alpha_pred_all = torch.cat([alpha_pred_all, alpha_pred.to("cpu")], dim=0)
    if alpha_only:
        return alpha_pred_all
    else:
        return orig_Y_all, X_duplicate_all, alpha_pred_all

In [ ]:
# find a threshold for g4 in val, and then test it on testset
val_loader = torch.utils.data.DataLoader(val_dataset, batch_size=8, num_workers=6, pin_memory=True)
model.eval()
val_orig_Y_all, val_X_duplicate_all, val_alpha_pred_all = compute_X_Y_alpha(model, val_loader)

In [5]:
print(val_alpha_pred_all)

tensor([[1.0000e+00, 1.0000e+00, 1.0000e+00, 1.0000e+00],
        [4.7568e+03, 1.0014e+00, 1.0057e+00, 1.0010e+00],
        [3.4225e+03, 1.3950e+00, 1.3448e+00, 1.0047e+00],
        ...,
        [1.0000e+00, 1.0000e+00, 1.0000e+00, 1.0000e+00],
        [1.0000e+00, 1.0869e+00, 1.1966e+04, 1.0000e+00],
        [3.8787e+03, 1.0104e+00, 1.0010e+00, 1.0939e+00]],
       grad_fn=<CatBackward0>)


In [6]:
def true_false_table(grd_truth, pred):
    table = [[[] for i in range(2)] for i in range(2)] # 
    for i in range(len(grd_truth)):
        if grd_truth[i] == 1:
            if pred[i] == 1: # True positive
                table[0][0].append(i)
            elif pred[i] == 0: # False negative
                table[0][1].append(i)
            else:
                KeyError('wrong number')
        elif grd_truth[i] == 0:
            if pred[i] == 1: # False positive
                table[1][0].append(i)
            elif pred[i] == 0: # True negative
                table[1][1].append(i)
            else:
                KeyError('wrong number')
        else:
            KeyError('wrong number')
    return table

In [7]:
# use maximum of alpha as threshold
# torch.concat(torch.max(alpha_pred_all, dim=1).values, grd_truth)
from sklearn.metrics import balanced_accuracy_score, accuracy_score, roc_auc_score
max_alpha = torch.max(val_alpha_pred_all, dim=1).values
output = [[],[],[],[]]
for threshold in np.linspace(5000,10000,100):
    pred = (torch.max(val_alpha_pred_all, dim=1).values < threshold).int()
    acc = balanced_accuracy_score(grd_truth, pred)
    acc2 = accuracy_score(grd_truth, pred)
    auc = roc_auc_score(grd_truth, pred)
    output[0].append(threshold)
    output[1].append(acc)
    output[2].append(acc2)
    output[3].append(auc)

index = output[1].index(max(output[1]))
print("###")
print(f'threshold:{output[0][index]}, balanced accuracy:{output[1][index]}, accuracy:{output[2][index]}, area under curve:{output[3][index]}')

pred = (torch.max(val_alpha_pred_all, dim=1).values < output[0][index]).int()
table = true_false_table(grd_truth, pred)
print('TP:',len(table[0][0]))
print('FN:',len(table[0][1]))
print('FP:',len(table[1][0]))
print('TN',len(table[1][1]))

###
threshold:2363.6363636363635, balanced accuracy:0.6407944662103946, accuracy:0.7613371694752706, area under curve:0.6407944662103945
TP: 226
FN: 223
FP: 1519
TN 5331


In [5]:
# see the performance on the test set
test_dataset = MapillaryDataset(test_df, transform = transform_val_test)
test_grd_truth = torch.tensor(test_df.region.isin(ood_regions).astype(int).values) # 0 as ID, 1 as OOD
test_loader = torch.utils.data.DataLoader(test_dataset, batch_size=8, num_workers=6, pin_memory=True)
model.eval()
test_orig_Y_all, test_X_duplicate_all, test_alpha_pred_all = compute_X_Y_alpha(model, test_loader)

In [9]:
# using max alpha as threshold, use data from ood_g4
from sklearn.metrics import balanced_accuracy_score, accuracy_score, roc_auc_score
threshold = 2353.53
max_alpha = torch.max(test_alpha_pred_all, dim=1).values
pred = (torch.max(test_alpha_pred_all, dim=1).values < threshold).int()
balanced_accuracy = balanced_accuracy_score(test_grd_truth, pred)
accuracy = accuracy_score(test_grd_truth, pred)
auc = roc_auc_score(test_grd_truth, pred)
print(f'threshold:{threshold}, balanced accuracy:{balanced_accuracy}, accuracy:{accuracy}, area under curve:{auc}')

table = true_false_table(test_grd_truth, pred)
print('TP:',len(table[0][0]))
print('FN:',len(table[0][1]))
print('FP:',len(table[1][0]))
print('TN',len(table[1][1]))

threshold:2353.53, balanced accuracy:0.6288994420271095, accuracy:0.7634, area under curve:0.6288994420271095
TP: 146
FN: 161
FP: 1022
TN 3671


In [ ]:
other_df = pd.read_csv('/lab/project-1/train_other_signs.csv').iloc[:5000]
test_df_less = pd.read_csv('/lab/project-1/test_label.csv').iloc[:2500]
full_df = pd.concat([test_df_less,other_df])
mix_sign_dataset = MapillaryDataset(full_df, transform = transform_val_test)
grd_truth1 = torch.tensor(test_df_less.region.isin(ood_regions).astype(int).values) # 0 as ID, 1 as OOD
grd_truth2 = torch.ones(500)
mix_grd_truth = torch.cat([grd_truth1, grd_truth2])
mix_sign_loader = torch.utils.data.DataLoader(mix_sign_dataset,
                                                      batch_size=32,
                                                      num_workers=6, pin_memory=True)
mix_orig_Y_all, mix_X_duplicate_all, mix_alpha_pred_all = compute_X_Y_alpha(model, mix_sign_loader)

In [7]:
# using max alpha as threshold, use data from ood_g4
from sklearn.metrics import balanced_accuracy_score, accuracy_score, roc_auc_score
threshold = 2353.53
max_alpha = torch.max(mix_alpha_pred_all, dim=1).values
pred = (torch.max(mix_alpha_pred_all, dim=1).values < threshold).int()
balanced_accuracy = balanced_accuracy_score(mix_grd_truth, pred)
accuracy = accuracy_score(mix_grd_truth, pred)
auc = roc_auc_score(mix_grd_truth, pred)
print(f'threshold:{threshold}, balanced accuracy:{balanced_accuracy}, accuracy:{accuracy}, area under curve:{auc}')

table = true_false_table(mix_grd_truth, pred)
print('TP:',len(table[0][0]))
print('FN:',len(table[0][1]))
print('FP:',len(table[1][0]))
print('TN',len(table[1][1]))

threshold:2353.53, balanced accuracy:0.5, accuracy:0.6933333333333334, area under curve:0.5
TP: 520
FN: 0
FP: 230
TN 0


In [8]:
mix_alpha_pred_all

tensor([[  1.0000,   1.0000,   1.0000,   1.0000],
        [  1.0000,   1.0000,   1.0000,   1.0000],
        [  1.0000,  21.3668, 404.6893,   1.0000],
        ...,
        [  2.2015,   1.1654,  69.9019,   1.0609],
        [  1.5390,   1.7932, 160.9585,   1.1464],
        [  1.3093,   3.1040, 393.3994,   1.0831]], grad_fn=<CatBackward0>)

In [46]:
other_alpha = mix_alpha_pred_all[-5000:]
threshold = 13666.67
max_alpha = torch.max(other_alpha, dim=1).values
pred = (torch.max(other_alpha, dim=1).values < threshold).int()
balanced_accuracy = balanced_accuracy_score(grd_truth2, pred)
accuracy = accuracy_score(grd_truth2, pred)
# auc = roc_auc_score(grd_truth2, pred)
print(f'threshold:{threshold}, balanced accuracy:{balanced_accuracy}, accuracy:{accuracy}, area under curve:{auc}')

table = true_false_table(grd_truth2, pred)
print('TP:',len(table[0][0]))
print('FN:',len(table[0][1]))
print('FP:',len(table[1][0]))
print('TN',len(table[1][1]))

threshold:13666.67, balanced accuracy:0.7494, accuracy:0.7494, area under curve:0.6786896243291592
TP: 3747
FN: 1253
FP: 0
TN 0


/nfs/homedirs/zhz/anaconda3/envs/postnet/lib/python3.10/site-packages/sklearn/metrics/_classification.py:2006: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")
